/**
 * ClickOra - OpenAPI 3.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.12
 * Contact: omkarbacha25@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    id?: number;
    username?: string;
    salutation?: User.SalutationEnum;
    firstName?: string;
    lastName?: string;
    email?: string;
    countryCode?: string;
    phone?: string;
    status?: User.StatusEnum;
    password?: string;
    LastLogin?: Date;
    rememberMe?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}
export namespace User {
    export type SalutationEnum = 'MR' | 'MRS' | 'MS' | 'MISS' | 'DR' | 'PROF' | 'ENGR' | 'MX' | 'NONE';
    export const SalutationEnum = {
        MR: 'MR' as SalutationEnum,
        MRS: 'MRS' as SalutationEnum,
        MS: 'MS' as SalutationEnum,
        MISS: 'MISS' as SalutationEnum,
        DR: 'DR' as SalutationEnum,
        PROF: 'PROF' as SalutationEnum,
        ENGR: 'ENGR' as SalutationEnum,
        MX: 'MX' as SalutationEnum,
        NONE: 'NONE' as SalutationEnum
    };
    export type StatusEnum = 'ACTIVE' | 'INACTIVE' | 'INVITED';
    export const StatusEnum = {
        ACTIVE: 'ACTIVE' as StatusEnum,
        INACTIVE: 'INACTIVE' as StatusEnum,
        INVITED: 'INVITED' as StatusEnum
    };
}